version: '3'

volumes:
  db-data:

networks:
  next-nest-app:
    name: next-nest-app
    driver: bridge

services:
  api:
    build: ./
    image: api
    container_name: api
    env_file:
      - .env.production
    ports:
      - '8080:8080'
    # restart: always
    depends_on:
      - redis
      - postgres
    networks:
      - next-nest-app
    # volumes:
    #   - ./:/app
    #   - /app/node_modules

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    # restart: always
    networks:
      - next-nest-app

  postgres:
    image: postgres
    container_name: postgres
    ports:
      - '5432:5432'
    # restart: always
    env_file:
      - .env.production
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - next-nest-app
